services:
  db:
    image: mongo
    restart: always
    ports:
      - '27037:27017'
    env_file:
      - ./apps/server/.env.local

    volumes:
      - afriHicker-data:/data/db

  db-adminer:
    image: mongo-express
    restart: always
    ports:
      - '8082:8081'
    env_file:
      - ./apps/server/.env.local

volumes:
  afriHicker-data:
